FROM mcr.microsoft.com/vscode/devcontainers/cpp:0-ubuntu-18.04

MAINTAINER Davide Desirello <davide.desirello@rai.it>

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
     && apt-get -y install python3-pip \
     libavahi-compat-libdnssd-dev \
     python3-setuptools
RUN pip3 install conan

#RUN sudo ln -s /home/vscode/.local/bin/conan /usr/local/bin/conan

#note use context ./nmos-cpp directory

COPY . /workspace/nmos-cpp

WORKDIR /workspace/nmos-cpp/build

RUN rm /workspace/nmos-cpp/build/CMakeCache.txt

RUN cmake ../Development -DCMAKE_BUILD_TYPE:STRING="debug"

RUN make -j 5

ENTRYPOINT /workspace/nmos-cpp/build/nmos-cpp-node node.json
